name: Build
on:
  push:
    branches:
      - client-branch
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  test:
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2
      - run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput=./test_coverage/ -l trx -r ./test_result/
